# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'

      - name: Build
        run: go build

      - uses: actions/cache@v3
        with:
          path: ./hometown-bot
          key: build-${{ github.workflow_sha }}

  deploy:
    runs-on: fuji
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./hometown-bot
          key: build-${{ github.workflow_sha }}

      - name: Deploy
        env:
          APP_DIR: ${{ secrets.APP_DIR }}
        run: ./deploy/deploy.sh


